### PR TITLE
Add support for IDs other than default 20 bytes

### PR DESCRIPTION
**Pull request by nazar-pc**
This is needed as part of implementation of custom hash functions (and ID space) support in `bittorrent-dht` package

### CODE REVIEW

**Comment by feross** [comment]
This is fine, but I changed the name from `idSpace` to `idLength`

**Comment by feross** [comment]
Oh, there's a bigger problem. Tests aren't passing anymore with this PR. @nazar-pc Any idea why?

**Comment by nazar-pc** [comment]
Will debug and rename property shortly

**Comment by feross** [comment]
Oh, the helper functions can't refer to `this` since they're not on the instance.

**Comment by feross** [comment]
Okay, I'll wait an updated PR.

**Comment by nazar-pc** [comment]
Should be better now

**Comment by feross** [comment]
LGTM, thanks!

**Comment by feross** [comment]
Released as 4.2.0

**Pull request merged**
