### PR TITLE
k-bucket@3

### PR DESCRIPTION
**Pull request by feross**
For performance improvements to .closest()

### CODE REVIEW

**Comment by mafintosh** [comment]
👍

**Comment by mafintosh** [comment]
3.8.0

**Comment by Arkotek** [comment]
Since I updated to k-rpc@3.8.0 I get the following error:

(I put a console .log in the method k-bucket/index.js:173):

```
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
<Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24>
{ id: <Buffer f5 bf 20 69 8e 68 47 98 73 32 7e 41 0e a1 a2 09 a9 a9 6d 24> }

/home/shant/gridcontrol/gridcontrol/node_modules/k-rpc/node_modules/k-bucket/index.js:173
  if (!Buffer.isBuffer(id)) throw new TypeError('id is not a Buffer')
                            ^

TypeError: id is not a Buffer
    at KBucket.closest (/home/shant/gridcontrol/gridcontrol/node_modules/k-rpc/node_modules/k-bucket/index.js:173:35)
    at DHT._ongetpeers (/home/shant/gridcontrol/gridcontrol/node_modules/bittorrent-dht/client.js:404:56)
    at DHT._onquery (/home/shant/gridcontrol/gridcontrol/node_modules/bittorrent-dht/client.js:371:19)
    at RPC.onquery (/home/shant/gridcontrol/gridcontrol/node_modules/bittorrent-dht/client.js:56:10)
    at emitTwo (events.js:100:13)
    at RPC.emit (events.js:185:7)
    at RPC.onquery (/home/shant/gridcontrol/gridcontrol/node_modules/k-rpc/index.js:66:10)
    at emitTwo (events.js:100:13)
    at RPC.emit (events.js:185:7)
    at Socket.onmessage (/home/shant/gridcontrol/gridcontrol/node_modules/k-rpc-socket/index.js:109:12)
```

**Comment by Arkotek** [comment]
it strongly seems to be correlated to that PR (https://github.com/mafintosh/k-rpc/pull/4/commits/5d93e1363bbaa73dc72ea517e0a4ee32bae37ba6)

**Comment by feross** [comment]
@Arkotek Are you using `k-rpc` directly? Or through `bittorrent-dht`?

**Comment by feross** [comment]
Sorry, just saw your stack trace. Investigating.

**Comment by feross** [comment]
@Arkotek Can you paste the output of `npm ls --depth=50` here? I need to know the exact version of `bittorrent-dht` and `k-rpc` you're using.

**Comment by feross** [comment]
@mafintosh I think that this PR should have been published as semver major, since the API changed to accept the buffer id directly instead of `{ id: xxxx }`.

So, users who lock the version of `bittorrent-dht` to exactly 7.1.0, or even `~7.1.0`, will be broke now because they'll get this newer k-rpc version since `bittorrent-dht` depends on `k-rpc` with `^`.

**Comment by feross** [comment]
Okay, this should be fixed now.

I unpublished `k-rpc` 3.8.0, so that users with pinned, old versions of `bittorrent-dht` will keep working.

I unpublished `bittorrent-dht` 7.2.0 which was depending on the now unpublished `k-rpc` at `^3.8.0`.

Then, published `k-rpc` 4.0.0 with the new code and `bittorrent-dht` 7.2.1 to go with it.

Yeesh.

**Comment by mafintosh** [comment]
@feross ah dang. good thing we caught it early

**Comment by feross** [comment]
Yeah! But even if it had been more than 24 hours and we couldn't unpublish, we could have fixed this by reverting the code and publishing as `k-rpc` 3.8.1.

Actually, maybe I should have done that. It would have avoided the need for unpublish.

**Pull request merged**
