### PR TITLE
Use `randombytes` package in order to avoid large overhead of `crypto` in browserify build

### PR DESCRIPTION
**Pull request by nazar-pc**
Before: 654 kB
After: 121 kB

### CODE REVIEW

**Comment by JakeChampion** [comment]
It looks to fail on new versions of Node due to a deprecated API being used.

**Comment by nazar-pc** [comment]
I'm on v7.10.0 right now - doesn't fail and doesn't complain about deprecations. Could you clarify what those deprecated APIs are?

**Comment by nazar-pc** [comment]
Updated to v8.1.2, still no errors and no deprecations

**Comment by feross** [comment]
Released as 4.2.0

**Pull request merged**
